/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectqtdl.flight;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import projectqtdl.user.login;

/**
 *
 * @author huynh
 */
public class adminFlight extends javax.swing.JFrame {
    /**
     * Creates new form buyTicket
     */
    public adminFlight() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        showFlight(flightModel.getAllFlight());
        showFrom(flightModel.getAllFrom());
        showTo(flightModel.getAllTo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        filterBtn = new javax.swing.JButton();
        fromFilter = new javax.swing.JComboBox<>();
        toFilter = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelFilterBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addTicketBtn = new javax.swing.JButton();
        deleteTicketBtn = new javax.swing.JButton();
        updateTicketBtn = new javax.swing.JButton();
        detailBtn = new javax.swing.JButton();
        detailBtn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bảng Vé");
        setBounds(new java.awt.Rectangle(0, 0, 940, 700));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setName("buyFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1010, 650));
        setSize(new java.awt.Dimension(1010, 650));

        jPanel1.setBackground(new java.awt.Color(19, 91, 160));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 600));

        filterBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filterBtn.setText("Lọc");
        filterBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        filterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterBtn.setEnabled(false);
        filterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterBtnMouseClicked(evt);
            }
        });
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });

        fromFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fromFilterItemStateChanged(evt);
            }
        });
        fromFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromFilterActionPerformed(evt);
            }
        });
        fromFilter.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fromFilterPropertyChange(evt);
            }
        });

        toFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toFilterItemStateChanged(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 600));

        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nơi đi", "Nơi đến", "Ngày đi", "Thời gian đi", "Số ghế", "Cổng", "Số chuyến bay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flightTable.setPreferredSize(new java.awt.Dimension(600, 400));
        flightTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                flightTablePropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(flightTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nơi đi:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nơi đến:");

        cancelFilterBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelFilterBtn.setText("Bỏ lọc");
        cancelFilterBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelFilterBtn.setBorderPainted(false);
        cancelFilterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelFilterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelFilterBtnMouseClicked(evt);
            }
        });
        cancelFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFilterBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(16, 91, 160));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        addTicketBtn.setBackground(new java.awt.Color(0, 102, 255));
        addTicketBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addTicketBtn.setForeground(new java.awt.Color(255, 255, 255));
        addTicketBtn.setText("Thêm chuyến bay");
        addTicketBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addTicketBtn.setBorderPainted(false);
        addTicketBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketBtnActionPerformed(evt);
            }
        });

        deleteTicketBtn.setBackground(new java.awt.Color(255, 51, 51));
        deleteTicketBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteTicketBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteTicketBtn.setText("Xóa chuyến bay");
        deleteTicketBtn.setBorder(null);
        deleteTicketBtn.setBorderPainted(false);
        deleteTicketBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteTicketBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTicketBtnMouseClicked(evt);
            }
        });
        deleteTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTicketBtnActionPerformed(evt);
            }
        });

        updateTicketBtn.setBackground(new java.awt.Color(0, 204, 102));
        updateTicketBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateTicketBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateTicketBtn.setText("Cập nhật chuyến bay");
        updateTicketBtn.setBorder(null);
        updateTicketBtn.setBorderPainted(false);
        updateTicketBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTicketBtnActionPerformed(evt);
            }
        });

        detailBtn.setBackground(new java.awt.Color(51, 51, 51));
        detailBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        detailBtn.setForeground(new java.awt.Color(255, 255, 255));
        detailBtn.setText("Xem chi tiết");
        detailBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        detailBtn.setBorderPainted(false);
        detailBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailBtnMouseClicked(evt);
            }
        });
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });

        detailBtn1.setBackground(new java.awt.Color(51, 0, 102));
        detailBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        detailBtn1.setForeground(new java.awt.Color(255, 255, 255));
        detailBtn1.setText("Đăng xuất");
        detailBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        detailBtn1.setBorderPainted(false);
        detailBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detailBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailBtn1MouseClicked(evt);
            }
        });
        detailBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(addTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateTicketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        addTicketBtn.getAccessibleContext().setAccessibleName("SoldBtn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QUẢN LÝ CHUYẾN BAY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(filterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fromFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(toFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(filterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cancelFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        filterBtn.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBtn1ActionPerformed

    private void detailBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBtn1MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_detailBtn1MouseClicked

    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBtnActionPerformed

    private void detailBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBtnMouseClicked
        // TODO add your handling code here:
        try{
            int row = this.flightTable.getSelectedRow();
            int id = Flight.getFlightIdInArr(row);
            new adminTicket(id, flightModel.getFlightById(id)).setVisible(true);
            dispose();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn vé để thay đổi");
        }
    }//GEN-LAST:event_detailBtnMouseClicked

    private void updateTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTicketBtnActionPerformed
        // TODO add your handling code here:
        try{
            int row = this.flightTable.getSelectedRow();
            int id = Flight.getFlightIdInArr(row);
            new flightForm(2, id).setVisible(true);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn vé để thay đổi");
        }
        //        new ticketForm(2, 0).setVisible(true);
    }//GEN-LAST:event_updateTicketBtnActionPerformed

    private void deleteTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTicketBtnActionPerformed
        // TODO add your handling code here:

//        showFlight(flightModel.getAllFlight());
    }//GEN-LAST:event_deleteTicketBtnActionPerformed

    private void deleteTicketBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTicketBtnMouseClicked
        // TODO add your handling code here:
        int row = flightTable.getSelectedRow();
        int id = Flight.getFlightIdInArr(row);
        JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn xóa ?");
        if(JOptionPane.YES_OPTION == 0) {
            flightModel.deleteFlight(id);
            DefaultTableModel model = (DefaultTableModel) flightTable.getModel();
            model.removeRow(row);
            Flight.deleteFlightById(row);
        }
    }//GEN-LAST:event_deleteTicketBtnMouseClicked

    private void addTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketBtnActionPerformed
        // TODO add your handling code here:
        new flightForm(1, 0).setVisible(true);
    }//GEN-LAST:event_addTicketBtnActionPerformed

    private void cancelFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFilterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelFilterBtnActionPerformed

    private void cancelFilterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelFilterBtnMouseClicked
        // TODO add your handling code here:
        fromFilter.setSelectedIndex(0);
        toFilter.setSelectedIndex(0);
        resetShowFlight();
        this.hideBtn(cancelFilterBtn);
    }//GEN-LAST:event_cancelFilterBtnMouseClicked

    private void flightTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_flightTablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_flightTablePropertyChange

    private void toFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toFilterItemStateChanged
        // TODO add your handling code here:
        if(toFilter.getSelectedItem() != "--")
        filterBtn.setEnabled(true);
        else if(fromFilter.getSelectedItem() == "--"){
            filterBtn.setEnabled(false);
            this.hideBtn(cancelFilterBtn);
            resetShowFlight();
        }
    }//GEN-LAST:event_toFilterItemStateChanged

    private void fromFilterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fromFilterPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fromFilterPropertyChange

    private void fromFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromFilterActionPerformed

    private void fromFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fromFilterItemStateChanged
        // TODO add your handling code here:
        if(fromFilter.getSelectedItem() != "--")
            filterBtn.setEnabled(true);
        else if(toFilter.getSelectedItem() == "--"){
            filterBtn.setEnabled(false);
            this.hideBtn(cancelFilterBtn);
            resetShowFlight();
        }
    }//GEN-LAST:event_fromFilterItemStateChanged

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_filterBtnActionPerformed

    private void filterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterBtnMouseClicked
        // TODO add your handling code here:
        ResultSet searchRs = flightModel.getSearchFlight(fromFilter.getSelectedItem().toString(), toFilter.getSelectedItem().toString());
        if(searchRs == null){
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy vé");
            return;
        }
        resetShowFlight(searchRs);
        this.showBtn(cancelFilterBtn, 60, 40);

    }//GEN-LAST:event_filterBtnMouseClicked
    
    private void hideBtn(javax.swing.JButton button) {
        button.setSize(0, 0);
    }
    
    private void showBtn(javax.swing.JButton button, int width, int height) {
        button.setSize(width, height);
    }
        
    public static void resetShowFlight() {
        showFlight(flightModel.getAllFlight()); 
    }
    
    public static void resetShowFlight(ResultSet rs) {
        showFlight(rs);
    }
    
    public static void showFrom(ResultSet froms){
        try{
            fromFilter.removeAllItems();
            fromFilter.addItem("--");
            int count = 1;
            while(froms.next()) {
                fromFilter.addItem(froms.getString(count));
            }
        }
        catch(SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public static void showTo(ResultSet tos){
        try{
            toFilter.removeAllItems();
            toFilter.addItem("--");
            int count = 1;
            while(tos.next()) {
                toFilter.addItem(tos.getString(count));
            }
        }
        catch(SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public static void showFlight(ResultSet flights) {
        try{
            Flight.renewFlightArr();
            DefaultTableModel model = (DefaultTableModel) flightTable.getModel();
            int count = 0;
            if(!flights.next()) {
                JOptionPane.showMessageDialog(null, "Không có chuyến bay bạn yêu cầu trong cơ sở dữ liệu");
                return;
            }
            do{ 
                String from = flights.getString("from");
                String to = flights.getString("to");
                String date = flights.getString("date");
                String boardingTime = flights.getString("boarding_time");
                String seat = flights.getString("seat") + "";
                String gate = flights.getString("gate");
                String flight = flights.getString("flight");
                
                Flight.addFlight(new Flight(from, to, date, boardingTime,Integer.parseInt(seat),gate, flight, flights.getInt("id")));
                
                model.setRowCount(count);
                count++;
                
                model.addRow(Flight.getFlightInArr(Flight.flightArr.size() - 1).getFLightVector());
            }while(flights.next());
        
            
        }
        catch(SQLException ex) {
            System.out.print(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTicketBtn;
    private static javax.swing.JButton cancelFilterBtn;
    private javax.swing.JButton deleteTicketBtn;
    private javax.swing.JButton detailBtn;
    private javax.swing.JButton detailBtn1;
    private static javax.swing.JButton filterBtn;
    private static javax.swing.JTable flightTable;
    private static javax.swing.JComboBox<String> fromFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JComboBox<String> toFilter;
    private javax.swing.JButton updateTicketBtn;
    // End of variables declaration//GEN-END:variables
}
