/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectqtdl.user;
import projectqtdl.flight.flightModel;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import projectqtdl.flight.flightPanel;
import projectqtdl.flight.Flight;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.*;
import projectqtdl.flight.bookForm;
import projectqtdl.flight.flightModel;

/**
 *
 * @author huynh
 */
public class userFlight extends javax.swing.JFrame {
    
    private int userId;
    private static Integer ticketId = 0;
    private static int  radioSelected = 0;
    private static ArrayList<flightPanel> flightArr;
    
    public userFlight(int id) {
        this.userId = id;
        initComponents();
        setLocationRelativeTo(null);
        this.jRadioButton3.setVisible(false);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        defaultJPane();
        showFrom(flightModel.getAllFrom());
        showTo(flightModel.getAllTo());
        this.usernameField.setText(UserModel.getUserById(this.userId));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cancelFilterBtn = new javax.swing.JButton();
        fromFilter = new javax.swing.JComboBox<>();
        toFilter = new javax.swing.JComboBox<>();
        filterBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        logoutBtn = new javax.swing.JButton();
        logoutBtn1 = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelcontain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Các chuyến bay");
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(880, 600));
        setSize(new java.awt.Dimension(900, 570));

        jPanel1.setBackground(new java.awt.Color(19, 91, 160));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 600));

        cancelFilterBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelFilterBtn.setText("Bỏ lọc");
        cancelFilterBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cancelFilterBtn.setBorderPainted(false);
        cancelFilterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelFilterBtn.setPreferredSize(new java.awt.Dimension(0, 0));
        cancelFilterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelFilterBtnMouseClicked(evt);
            }
        });
        cancelFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelFilterBtnActionPerformed(evt);
            }
        });

        fromFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fromFilterItemStateChanged(evt);
            }
        });
        fromFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromFilterActionPerformed(evt);
            }
        });
        fromFilter.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fromFilterPropertyChange(evt);
            }
        });

        toFilter.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toFilterItemStateChanged(evt);
            }
        });

        filterBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filterBtn.setText("Lọc");
        filterBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        filterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filterBtn.setEnabled(false);
        filterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterBtnMouseClicked(evt);
            }
        });
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nơi đến:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nơi đi:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hình thức thanh toán");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Thanh toán online");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Thanh toán trực tiếp");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutBtn.setText("Vé của tôi");
        logoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutBtn.setBorderPainted(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        logoutBtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutBtn1.setText("Đăng xuất");
        logoutBtn1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutBtn1.setBorderPainted(false);
        logoutBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtn1MouseClicked(evt);
            }
        });
        logoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn1ActionPerformed(evt);
            }
        });

        usernameField.setEditable(false);
        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Đặt vé");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MUA VÉ");

        panelcontain.setLayout(new java.awt.GridLayout(0, 1, 0, 8));
        jScrollPane1.setViewportView(panelcontain);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 174, Short.MAX_VALUE)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(toFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelFilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(fromFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(toFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cancelFilterBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(logoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelFilterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelFilterBtnMouseClicked
        // TODO add your handling code here:
        fromFilter.setSelectedIndex(0);
        toFilter.setSelectedIndex(0);
        this.hideBtn(cancelFilterBtn);
        defaultJPane();
    }//GEN-LAST:event_cancelFilterBtnMouseClicked

    private void cancelFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelFilterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelFilterBtnActionPerformed

    private void fromFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fromFilterItemStateChanged
        // TODO add your handling code here:
        if(fromFilter.getSelectedItem() != "--"){
            filterBtn.setEnabled(true);
        }
        else if(toFilter.getSelectedItem() == "--"){
            filterBtn.setEnabled(false);
            this.hideBtn(cancelFilterBtn);
        }
    }//GEN-LAST:event_fromFilterItemStateChanged

    private void fromFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromFilterActionPerformed

    private void fromFilterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fromFilterPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fromFilterPropertyChange

    private void toFilterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toFilterItemStateChanged
        // TODO add your handling code here:
        if(toFilter.getSelectedItem() != "--"){
            filterBtn.setEnabled(true);
        }
        else if(fromFilter.getSelectedItem() == "--"){
            filterBtn.setEnabled(false);
            this.hideBtn(cancelFilterBtn);
        }
    }//GEN-LAST:event_toFilterItemStateChanged

    
    public static void chooseTicket(int id) {
        ticketId = id;
        for(flightPanel flightpanel : flightArr){
            if(flightpanel.getId() != id){
                flightpanel.unChoose();
            }
        }
    }
    
    public static void defaultJPane() {
        JPanel defaultPane = new javax.swing.JPanel();
        defaultPane.setBackground(new java.awt.Color(255, 255, 255));
        JLabel defaultLabel = new javax.swing.JLabel();
        defaultPane.add(defaultLabel);
        defaultLabel.setBackground(new java.awt.Color(255, 255, 255));
        defaultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defaultLabel.setText("HÃY CHỌN NƠI ĐI NƠI ĐẾN");
        defaultPane.setSize(600, 400);
        panelcontain.add(defaultPane);
    }
    
    private void hideBtn(javax.swing.JButton button) {
        button.setSize(0, 0);
    }
    
    private void showBtn(javax.swing.JButton button, int width, int height) {
        button.setSize(width, height);
    }
    
    public static void showFrom(ResultSet froms){
        try{
            fromFilter.removeAll();
            fromFilter.addItem("--");
            int count = 1;
            while(froms.next()) {
                fromFilter.addItem(froms.getString(count));
            }
        }
        catch(SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public static void showTo(ResultSet tos){
        try{
            toFilter.removeAllItems();
            toFilter.addItem("--");
            int count = 1;
            while(tos.next()) {
                toFilter.addItem(tos.getString(count));
            }
        }
        catch(SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public static void showFlightPanel(ResultSet flights){
        try{
            flightArr = new ArrayList<flightPanel>();
            jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            panelcontain.removeAll();
            int sumHeight = 0;
            if(!flights.next()) {
                JOptionPane.showMessageDialog(null, "Không tìm thấy  nơi đi nơi đến bạn yêu cầu");
                return;
            }
            else do{
                String from = flights.getString("from");
                String to = flights.getString("to");
                String date = flights.getString("date");
                String time = flights.getString("boarding_time");
                String flight = flights.getString("flight");
                String seat = flights.getInt("seat") + "";
                String gate = flights.getString("gate");
                int id = flights.getInt("id");
                flightArr.add(new flightPanel(new Flight(from, to, date, time, Integer.parseInt(seat), gate, flight, id)));
                flightPanel temp = flightArr.get(flightArr.size() - 1);
                temp.setSize(new Dimension(600, 170));
                sumHeight += 170;
                panelcontain.add(temp);
                }   while(flights.next());
            int scrollHeight = panelcontain.getHeight();
                if(sumHeight < scrollHeight) {
                    JPanel addSpace = new JPanel();
                    addSpace.setSize(600, scrollHeight - sumHeight - 200);
                    panelcontain.add(addSpace);   
            }
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    
    
    private void filterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterBtnMouseClicked
        // TODO add your handling code here:
        ResultSet searchRs = flightModel.getSearchFlight(fromFilter.getSelectedItem().toString(), toFilter.getSelectedItem().toString());
        this.showBtn(cancelFilterBtn, 60, 40);
        this.showFlightPanel(searchRs);
        
    }//GEN-LAST:event_filterBtnMouseClicked

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_filterBtnActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(ticketId == -1){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn chuyến bay");
            return;
        }
        
        if(radioSelected == 0){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn hình thức thanh toán");
            return;
        }
        
        new bookForm(flightModel.getFlightById(ticketId), radioSelected, userId).setVisible(true);
        
            
    }//GEN-LAST:event_jButton1MouseClicked

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        // TODO add your handling code here:
        new userTicket(this.userId).setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void logoutBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtn1MouseClicked
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtn1MouseClicked

    private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        if(radioSelected == 2) {
            radioSelected = 0;
            this.jRadioButton3.doClick();
        }
        else radioSelected = 2;
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        if(radioSelected == 1) {
            radioSelected = 0;
            this.jRadioButton3.doClick();
        }
        else radioSelected = 1;
    }//GEN-LAST:event_jRadioButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private static javax.swing.JButton cancelFilterBtn;
    private static javax.swing.JButton filterBtn;
    private static javax.swing.JComboBox<String> fromFilter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton logoutBtn1;
    private static javax.swing.JPanel panelcontain;
    private static javax.swing.JComboBox<String> toFilter;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
